// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCZx8FU_snN3fH7eIXQAYVIidID3fT0Mjs',
    appId: '1:913657507795:android:e47c969ecfc6aa3ce80926',
    messagingSenderId: '913657507795',
    projectId: 'dialysisnow-32ecf',
    databaseURL: 'https://dialysisnow-32ecf-default-rtdb.firebaseio.com',
    storageBucket: 'dialysisnow-32ecf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBEypy7C7oIVnWM5y9GOr_gYui-lOCI3Ek',
    appId: '1:913657507795:ios:2cb0386d10dbb322e80926',
    messagingSenderId: '913657507795',
    projectId: 'dialysisnow-32ecf',
    databaseURL: 'https://dialysisnow-32ecf-default-rtdb.firebaseio.com',
    storageBucket: 'dialysisnow-32ecf.appspot.com',
    iosClientId: '913657507795-7ibkn1coktlk9rq4iimi1tcsosev8ek1.apps.googleusercontent.com',
    iosBundleId: 'com.DialysisNow',
  );
}
